// Code generated by goctl. DO NOT EDIT.
package types

type AgentTaskCloseReq struct {
	Id          string `json:"id"`
	CallBackUrl string `json:"call_back_url"`
}

type AgentTaskCloseResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type AgentTaskListReq struct {
}

type AgentTaskListResp struct {
	Success bool                    `json:"success"`
	Message string                  `json:"message"`
	Data    []AgentTaskListRespData `json:"data"`
}

type AgentTaskListRespData struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	ListenPort string `json:"listen_port"`
	Status     string `json:"status"`
	StartTime  string `json:"start_time"`
	EndTime    string `json:"end_time"`
	Duration   string `json:"duration"`
}

type AgentTaskRunRespData struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	ListenPort string `json:"listen_port"`
	Status     string `json:"status"`
	StartTime  string `json:"start_time"`
	EndTime    string `json:"end_time"`
	Duration   string `json:"duration"`
}

type AgentTaskStartReq struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	CallBackUrl string `json:"call_back_url"`
	EndTime     string `json:"end_time"`
	ListenPort  string `json:"listen_port"`
}

type AgentTaskStartResp struct {
	Success bool                 `json:"success"`
	Message string               `json:"message"`
	Data    AgentTaskRunRespData `json:"data"`
}

type AgentTaskStopReq struct {
	Id          string `json:"id"`
	CallBackUrl string `json:"call_back_url"`
}

type AgentTaskStopResp struct {
	Success bool                  `json:"success"`
	Message string                `json:"message"`
	Data    AgentTaskStopRespData `json:"data"`
}

type AgentTaskStopRespData struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}
