// Code generated by goctl. DO NOT EDIT.
package types

type AuthCodesResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type AuthLoginReq struct {
	Username      string `json:"username"`
	Password      string `json:"password"`
	SelectAccount string `json:"selectAccount"`
	Captcha       bool   `json:"captcha"`
}

type AuthLoginResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
	Error   string      `json:"error"`
}

type AuthLogoutReq struct {
}

type AuthLogoutResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type EdiResourceAgentSyncReq struct {
	Id                    string  `json:"id"`
	IP                    string  `json:"ip"`
	Hostname              string  `json:"hostname"`
	CPUCores              int     `json:"cpu_cores"`
	CPUUsedPercent        float64 `json:"cpu_used_percent"`
	CPUFreePercent        float64 `json:"cpu_free_percent"`
	MemoryTotal           uint64  `json:"memory_total"`
	MemoryUsed            uint64  `json:"memory_used"`
	MemoryFree            uint64  `json:"memory_free"`
	MemoryUsedPercent     float64 `json:"memory_used_percent"`
	NetworkBytesSent      uint64  `json:"network_bytes_sent"`
	NetworkBytesReceive   uint64  `json:"network_bytes_receive"`
	NetworkPacketsSent    uint64  `json:"network_packets_sent"`
	NetworkPacketsReceive uint64  `json:"network_packets_receive"`
	Status                string  `json:"status"`
}

type EdiResourceAgentSyncResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type EdiTaskRecordyncReq struct {
	Id          string `json:"id"`
	Status      string `json:"status"`
	FailReason  string `json:"fail_reason,optional"`
	ExecuteTime string `json:"execute_time,optional"`
}

type EdiTaskRecordyncResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type EdiTrafficPoolSyncReq struct {
	Id              string `json:"id"`
	ResponseHeaders string `json:"response_headers"`
	ResponseBody    string `json:"response_body"`
	RequestHeaders  string `json:"request_headers"`
	RequestBody     string `json:"request_body"`
	Method          string `json:"method"`
	Url             string `json:"url"`
	TaskId          string `json:"task_id"`
	TaskName        string `json:"task_name"`
	HttpType        string `json:"http_type"`
}

type EdiTrafficPoolSyncResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type ResourceAgentConsoleReq struct {
	ID string `path:"id`
}

type ResourceAgentConsoleResp struct {
	Success bool                        `json:"success"`
	Message string                      `json:"message"`
	Data    ResourceAgentDetailRespData `json:"data" `
}

type ResourceAgentConsoleRespData struct {
	ID             string `json:"id"`          // 执行机ID
	Name           string `json:"name"`        // 执行机名称
	Description    string `json:"description"` // 描述信息
	Ip             string `json:"ip"`
	Cpu            int    `json:"cpu"`
	Memory         int    `json:"memory"`
	Network        int    `json:"network"`
	Disk           int    `json:"disk"`
	Status         string `json:"status"`
	LastReportTime string `json:"last_report_time"`
}

type ResourceAgentCreateReq struct {
	Name            string `json:"name"`                 // 执行机名称
	Description     string `json:"description,optional"` // 描述信息
	SelectedAgentId string `json:"selected_agent_id"`
}

type ResourceAgentCreateResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type ResourceAgentDetailReq struct {
	ID string `path:"id"` // 关键点：path 标签表示路径参数
}

type ResourceAgentDetailResp struct {
	Success bool                        `json:"success"`
	Message string                      `json:"message"`
	Data    ResourceAgentDetailRespData `json:"data" `
}

type ResourceAgentDetailRespData struct {
	ID          string `json:"id"`          // 执行机ID
	Name        string `json:"name"`        // 执行机名称
	Description string `json:"description"` // 描述信息
}

type ResourceAgentDetailV2Req struct {
	ID string `path:"id"` // 关键点：path 标签表示路径参数
}

type ResourceAgentDetailV2Resp struct {
	Success bool                          `json:"success"`
	Message string                        `json:"message"`
	Data    ResourceAgentDetailV2RespData `json:"data" `
}

type ResourceAgentDetailV2RespData struct {
	ID                    string                              `json:"id"`          // 执行机ID
	Name                  string                              `json:"name"`        // 执行机名称
	Description           string                              `json:"description"` // 描述信息
	Ip                    string                              `json:"ip"`
	StartTime             string                              `json:"start_time"`
	StopTime              string                              `json:"stop_time"`
	CPUCores              int                                 `json:"cpu_cores"`
	CPUUsedPercent        float64                             `json:"cpu_used_percent"`
	CPUFreePercent        float64                             ` json:"cpu_free_percent"`
	MemoryTotal           float64                             ` json:"memory_total"`
	MemoryUsed            float64                             ` json:"memory_used"`
	MemoryFree            float64                             ` json:"memory_free"`
	MemoryUsedPercent     float64                             ` json:"memory_used_percent"`
	NetworkBytesSent      float64                             ` json:"network_bytes_sent"`
	NetworkBytesReceive   float64                             `json:"network_bytes_receive"`
	NetworkPacketsSent    float64                             ` json:"network_packets_sent"`
	NetworkPacketsReceive float64                             ` json:"network_packets_receive"`
	Status                string                              `json:"status"`
	LastReportTime        string                              `json:"last_report_time"`
	IdentificationCode    string                              `json:"identification_code"`
	Tasks                 []ResourceAgentDetailV2RespDataTask `json:"tasks"`
}

type ResourceAgentDetailV2RespDataTask struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description"`
	Status       string `json:"status"`
	StartTime    string `json:"start_time"`
	EndTime      string `json:"end_time"`
	Type         string `json:"type"`
	RuleId       string `json:"rule_id"`
	RuleName     string `json:"rule_name"`
	StrategyId   string `json:"strategy_id"`
	StrategyName string `json:"strategy_name"`
}

type ResourceAgentQueryPageReq struct {
	PageSize      int    `json:"page_size"` //页最大数量
	Page          int    `json:"page"`      //当前页
	Keyword       string `json:"keyword"`   // 关键字
	ExecuteStatus string `json:"execute_status,optional"`
	Status        string `json:"status,optional"` // 状态 (offline:离线, healthy:健康, warning:警告, error:异常 created:待部署)
}

type ResourceAgentQueryPageResp struct {
	Success bool                           `json:"success"`
	Message string                         `json:"message"`
	Data    ResourceAgentQueryPageRespData `json:"data"`
}

type ResourceAgentQueryPageRespBoard struct {
	Total   int `json:"total"`   // 总数
	Healthy int `json:"healthy"` // 健康数量
	Warning int `json:"warning"` // 警告数量
	Error   int `json:"error"`   // 异常数量
	Offline int `json:"offline"` // 离线数量
}

type ResourceAgentQueryPageRespData struct {
	Board   ResourceAgentQueryPageRespBoard    `json:"board"`   // 状态看板
	Total   int                                `json:"total"`   // 总数
	Records []ResourceAgentQueryPageRespRecord `json:"records"` // 记录列表
}

type ResourceAgentQueryPageRespRecord struct {
	ID                    string  `json:"id"`          // 执行机ID
	Name                  string  `json:"name"`        // 执行机名称
	IP                    string  `json:"ip"`          // IP地址
	Description           string  `json:"description"` // 描述信息
	ExecuteStatus         string  `json:"execute_status"`
	Status                string  `json:"status"`           // 状态 (offline:离线, healthy:健康, warning:警告, error:异常 created:待部署)
	LastReportTime        string  `json:"last_report_time"` // 最后上报时间
	StartTime             string  `json:"start_time"`
	StopTime              string  `json:"stop_time"`
	CPUCores              int     `json:"cpu_cores"`
	CPUUsedPercent        float64 `json:"cpu_used_percent"`
	CPUFreePercent        float64 ` json:"cpu_free_percent"`
	MemoryTotal           float64 ` json:"memory_total"`
	MemoryUsed            float64 ` json:"memory_used"`
	MemoryFree            float64 ` json:"memory_free"`
	MemoryUsedPercent     float64 ` json:"memory_used_percent"`
	NetworkBytesSent      float64 ` json:"network_bytes_sent"`
	NetworkBytesReceive   float64 `json:"network_bytes_receive"`
	NetworkPacketsSent    float64 ` json:"network_packets_sent"`
	NetworkPacketsReceive float64 ` json:"network_packets_receive"`
}

type ResourceAgentSelectOptionsReq struct {
	Keyword       string   `json:"keyword,optional"`
	Status        []string `json:"status,optional"`
	ExecuteStatus []string `json:"execute_status,optional"`
}

type ResourceAgentSelectOptionsResp struct {
	Success bool                                 `json:"success"`
	Message string                               `json:"message"`
	Data    []ResourceAgentSelectOptionsRespData `json:"data" `
}

type ResourceAgentSelectOptionsRespData struct {
	Id            string `json:"id"`
	Key           string `json:"key"`
	Value         string `json:"value"`
	ExecuteStatus string `json:"execute_status"`
}

type ResourceAgentUpdateReq struct {
	Id          string `json:"id"`
	Name        string `json:"name"`                 // 执行机名称
	Description string `json:"description,optional"` // 描述信息
}

type ResourceAgentUpdateResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type TaskRecordCreateReq struct {
	Name        string                       `json:"name"`                 // 录制任务名称
	Description string                       `json:"description,optional"` // 描述信息
	Strategy    *TaskRecordCreateReqStrategy `json:"strategy"`             // 录制策略id
	Agent       *TaskRecordCreateReqAgent    `json:"agent"`
	RecordTime  []string                     `json:"record_time"`
	ListenPort  string                       `json:"listen_port"`
}

type TaskRecordCreateReqAgent struct {
	Id            string `json:"id"`
	Key           string `json:"key"`
	Value         string `json:"value"`
	ExecuteStatus string `json:"execute_status"`
}

type TaskRecordCreateReqStrategy struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

type TaskRecordCreateResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type TaskRecordDetailReq struct {
	ID string `path:"id"` // 关键点：path 标签表示路径参数
}

type TaskRecordDetailResp struct {
	Success bool                     `json:"success"`
	Message string                   `json:"message"`
	Data    TaskRecordDetailRespData `json:"data" `
}

type TaskRecordDetailRespData struct {
	ID           string `json:"id"`          // 录制任务ID
	Name         string `json:"name"`        // 录制任务名称
	Description  string `json:"description"` // 描述信息
	Status       string `json:"status"`
	StrategyId   string `json:"strategy_id"`
	StrategyName string `json:"strategy_name"`
	StartTime    string `json:"start_time"`
	EndTime      string `json:"end_time"`
	CreateTime   string `json:"create_time"`
	UpdateTime   string `json:"update_time"`
	CreateBy     string `json:"create_by"`
	UpdateBy     string `json:"update_by"`
	CreateByName string `json:"create_by_name"`
	UpdateByName string `json:"update_by_name"`
	AgentId      string `json:"agent_id"`
	AgentName    string `json:"agent_name"`
}

type TaskRecordExecuteReq struct {
	ID string `path:"id"`
}

type TaskRecordExecuteResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type TaskRecordQueryPageReq struct {
	PageSize        int      `json:"page_size"`         //页最大数量
	Page            int      `json:"page"`              //当前页
	Keyword         string   `json:"keyword"`           // 关键字
	Strategy        string   `json:"strategy,optional"` // 录制策略
	Rule            string   `json:"rule,optional"`     // 录制规则
	Status          string   `json:"status,optional"`
	CreateTimeRaneg []string `json:"create_time_range,optional"` // 创建时间范围
}

type TaskRecordQueryPageResp struct {
	Success bool                        `json:"success"`
	Message string                      `json:"message"`
	Data    TaskRecordQueryPageRespData `json:"data"`
}

type TaskRecordQueryPageRespData struct {
	Total   int                             `json:"total"`   // 总数
	Records []TaskRecordQueryPageRespRecord `json:"records"` // 记录列表
}

type TaskRecordQueryPageRespRecord struct {
	Id           string `json:"id"`   // 录制任务Id
	Name         string `json:"name"` // 录制任务名称
	Status       string `json:"status"`
	StrategyCode string `json:"strategy_code"`
	StrategyName string `json:"strategy_name"`
	StartTime    string `json:"start_time"`
	EndTime      string `json:"end_time"`
	AgentId      string `json:"agent_id"`
	AgentName    string `json:"agent_name"`
	ListenPort   string `json:"listen_port"`
	ExecuteTime  string `json:"execute_time"`
}

type TaskRecordUpdateReq struct {
	Id           string `json:"id"`
	Name         string `json:"name"`                 // 录制任务名称
	Description  string `json:"description,optional"` // 描述信息
	StrategyId   string `json:"strategy_id"`          // 录制策略id
	StrategyName string `json:"strategy_name"`        // 录制策略名称
	AgentId      string `json:"agent_id"`
	AgentName    string `json:"agent_name"`
}

type TaskRecordUpdateResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type TrafficPoolDetailReq struct {
}

type TrafficPoolDetailResp struct {
}

type TrafficPoolQueryPageReq struct {
	PageSize        int      `json:"page_size"`         //页最大数量
	Page            int      `json:"page"`              //当前页
	Keyword         string   `json:"keyword"`           // 关键字
	Method          string   `json:"method,optional"`   //请求方式
	RecordTimeRange []string `json:"record_time_range"` //录制时间
}

type TrafficPoolQueryPageResp struct {
	Success bool                         `json:"success"`
	Message string                       `json:"message"`
	Data    TrafficPoolQueryPageRespData `json:"data"`
}

type TrafficPoolQueryPageRespData struct {
	Total   int                                  `json:"total"`
	Records []TrafficPoolQueryPageRespDataRecord `json:"records"`
}

type TrafficPoolQueryPageRespDataRecord struct {
	Id              string `json:"id"`
	Url             string `json:"url"`
	RequestBody     string `json:"request_body"`
	RequestHeaders  string `json:"request_headers"`
	ResponseBody    string `json:"response_body"`
	ResponseHeaders string `json:"response_headers"`
	Method          string `json:"method"`
	HttpType        string `json:"http_type"`
	RecordTime      string `json:"record_time"`
	RecordTaskId    string `json:"record_task_id"`
	RecordTaskName  string `json:"record_task_name"`
}

type UserInfoRequest struct {
}

type UserInfoResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
