// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	agent "github.com/qianjisantech/gosmo-agent/internal/handler/agent"
	"github.com/qianjisantech/gosmo-agent/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/task/start",
				Handler: agent.AgentTaskStartHandler(serverCtx),
			},
		},
		rest.WithPrefix("/agent"),
	)
}
