// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "osmo/internal/handler/auth"
	polarisresource "osmo/internal/handler/polaris/resource"
	polaristask "osmo/internal/handler/polaris/task"
	polaristraffic "osmo/internal/handler/polaris/traffic"
	system "osmo/internal/handler/system"
	"osmo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/codes",
				Handler: auth.AuthCodesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.AuthLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/logout",
				Handler: auth.AuthLogoutHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/console/:id",
				Handler: polarisresource.ResourceAgentConsoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: polarisresource.ResourceAgentCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: polarisresource.ResourceAgentDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail/v2/:id",
				Handler: polarisresource.ResourceAgentDetailV2Handler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/page",
				Handler: polarisresource.ResourceAgentQueryPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/select/options",
				Handler: polarisresource.ResourceAgentSelectOptionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: polarisresource.ResourceAgentUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/polaris/resource/agent"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/create",
				Handler: polaristask.TaskRecordCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: polaristask.TaskRecordDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/execute/:id",
				Handler: polaristask.TaskRecordExecuteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/page",
				Handler: polaristask.TaskRecordQueryPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: polaristask.TaskRecordUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/polaris/task/record"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/detail/:id",
				Handler: polaristraffic.TrafficPoolDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/page",
				Handler: polaristraffic.TrafficPoolQueryPageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/polaris/traffic/pool"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/info",
				Handler: system.UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/system"),
	)
}
