// Code generated by goctl. DO NOT EDIT.
package types

type AuthLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthLoginResp struct {
	Success bool              `json:"success"`
	Message string            `json:"message"`
	Data    AuthLoginRespData `json:"data"`
}

type AuthLoginRespData struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

type AuthRegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

type AuthRegisterResp struct {
	Success bool                 `json:"success"`
	Message string               `json:"message"`
	Data    AuthRegisterRespData `json:"data"`
}

type AuthRegisterRespData struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}
