// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	config "polaris/internal/handler/config"
	discovery "polaris/internal/handler/discovery"
	task "polaris/internal/handler/task"
	"polaris/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/hostloading",
				Handler: config.ConfigHotLoadingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/polaris/config"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/agent/heatbeat/:identification_code",
				Handler: discovery.DiscoveryHeatBeatHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/agent/register",
				Handler: discovery.DiscoveryRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/polaris/v1/discovery"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/run/callback",
				Handler: task.AgentRecordTaskRunCallBackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync",
				Handler: task.AgentRecordTaskSyncHandler(serverCtx),
			},
		},
		rest.WithPrefix("/polaris/agent/task"),
	)
}
