// Code generated by goctl. DO NOT EDIT.
package types

type ConfigHotLoadingReq struct {
}

type ConfigHotLoadingResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type DiscoveryHeatBeatReq struct {
	IdentificationCode    string  `path:"identification_code"`
	IP                    string  `json:"ip"`
	Status                string  `json:"status"`
	Hostname              string  `json:"hostname"`
	CPUCores              int     `json:"cpu_cores"`
	CPUUsedPercent        float64 `json:"cpu_used_percent"`
	CPUFreePercent        float64 ` json:"cpu_free_percent"`
	MemoryTotal           int64   ` json:"memory_total"`
	MemoryUsed            int64   ` json:"memory_used"`
	MemoryFree            int64   ` json:"memory_free"`
	MemoryUsedPercent     float64 ` json:"memory_used_percent"`
	NetworkBytesSent      int64   ` json:"network_bytes_sent"`
	NetworkBytesReceive   int64   `json:"network_bytes_receive"`
	NetworkPacketsSent    int64   ` json:"network_packets_sent"`
	NetworkPacketsReceive int64   ` json:"network_packets_receive"`
}

type DiscoveryHeatBeatResp struct {
	Success bool                      `json:"success"`
	Message string                    `json:"message"`
	Data    DiscoveryHeatBeatRespData `json:"data"`
}

type DiscoveryHeatBeatRespData struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

type DiscoveryRegisterReq struct {
	IP                    string  `json:"ip"`
	Hostname              string  `json:"hostname"`
	CPUCores              int     `json:"cpu_cores"`
	CPUUsedPercent        float64 `json:"cpu_used_percent"`
	CPUFreePercent        float64 ` json:"cpu_free_percent"`
	MemoryTotal           int64   ` json:"memory_total"`
	MemoryUsed            int64   ` json:"memory_used"`
	MemoryFree            int64   ` json:"memory_free"`
	MemoryUsedPercent     float64 ` json:"memory_used_percent"`
	NetworkBytesSent      int64   ` json:"network_bytes_sent"`
	NetworkBytesReceive   int64   `json:"network_bytes_receive"`
	NetworkPacketsSent    int64   ` json:"network_packets_sent"`
	NetworkPacketsReceive int64   ` json:"network_packets_receive"`
}

type DiscoveryRegisterResp struct {
	Success bool                      `json:"success"`
	Message string                    `json:"message"`
	Data    DiscoveryRegisterRespData `json:"data"`
}

type DiscoveryRegisterRespData struct {
	Id                    string  `json:"id"`
	IP                    string  `json:"ip"`
	Hostname              string  `json:"hostname"`
	CPUCores              int     `json:"cpu_cores"`
	CPUUsedPercent        float64 `json:"cpu_used_percent"`
	CPUFreePercent        float64 ` json:"cpu_free_percent"`
	MemoryTotal           int64   ` json:"memory_total"`
	MemoryUsed            int64   ` json:"memory_used"`
	MemoryFree            int64   ` json:"memory_free"`
	MemoryUsedPercent     float64 ` json:"memory_used_percent"`
	NetworkBytesSent      int64   ` json:"network_bytes_sent"`
	NetworkBytesReceive   int64   `json:"network_bytes_receive"`
	NetworkPacketsSent    int64   ` json:"network_packets_sent"`
	NetworkPacketsReceive int64   ` json:"network_packets_receive"`
	IdentificationCode    string  `json:"identification_code"`
}

type TaskRunCallBackReq struct {
	Id        string `json:"id"`
	Status    string `json:"status"`
	Message   string `json:"message"`
	Name      string `json:"name"`
	Success   bool   `json:"success"`
	Timestamp string `json:"timestamp"`
}

type TaskRunCallBackResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}
