// Code generated by goctl. DO NOT EDIT.
package types

type AgentRecordTaskRunCallBackReq struct {
	Id        string `json:"id"`
	Status    string `json:"status"`
	Message   string `json:"message"`
	Name      string `json:"name"`
	Success   bool   `json:"success"`
	Timestamp string `json:"timestamp"`
}

type AgentRecordTaskRunCallBackResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type AgentRecordTaskSyncReq struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Description  string `json:"description,optional"`
	ListenPort   string `json:"listen_port"`
	Status       string `json:"status"`
	CreateTime   string `json:"create_time"`
	UpdateTime   string `json:"update_time"`
	CreateBy     string `json:"create_by"`
	CreateByName string `json:"create_by_name"`
	UpdateBy     string `json:"update_by"`
	UpdateByName string `json:"update_by_name"`
	StartTime    string `json:"start_time"`
	EndTime      string `json:"end_time"`
	AgentId      string `json:"agent_id"`
	AgentName    string `json:"agent_name"`
	ExecuteTime  string `json:"execute_time"`
	TaskType     string `json:"task_type,optional"`
}

type AgentRecordTaskSyncResp struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type ConfigHotLoadingReq struct {
}

type ConfigHotLoadingResp struct {
	Success bool        `json:"success"`
	Message string      `json:"message"`
	Data    interface{} `json:"data"`
}

type DiscoveryHeatBeatReq struct {
	IdentificationCode    string  `path:"identification_code"`
	IP                    string  `json:"ip"`
	Status                string  `json:"status"`
	Hostname              string  `json:"hostname"`
	CPUCores              int     `json:"cpu_cores"`
	CPUUsedPercent        float64 `json:"cpu_used_percent"`
	CPUFreePercent        float64 ` json:"cpu_free_percent"`
	MemoryTotal           int64   ` json:"memory_total"`
	MemoryUsed            int64   ` json:"memory_used"`
	MemoryFree            int64   ` json:"memory_free"`
	MemoryUsedPercent     float64 ` json:"memory_used_percent"`
	NetworkBytesSent      int64   ` json:"network_bytes_sent"`
	NetworkBytesReceive   int64   `json:"network_bytes_receive"`
	NetworkPacketsSent    int64   ` json:"network_packets_sent"`
	NetworkPacketsReceive int64   ` json:"network_packets_receive"`
}

type DiscoveryHeatBeatResp struct {
	Success bool                      `json:"success"`
	Message string                    `json:"message"`
	Data    DiscoveryHeatBeatRespData `json:"data"`
}

type DiscoveryHeatBeatRespData struct {
	Id    string                          `json:"id"`
	Name  string                          `json:"name"`
	Tasks []DiscoveryHeatBeatRespDataTask `json:"tasks"`
}

type DiscoveryHeatBeatRespDataTask struct {
	Id           string `json:"id"`
	Name         string `json:"name"`
	Status       string `json:"status"`
	ListenPort   int    `json:"listen_port"`
	CreateTime   string `json:"create_time"`
	CreateBy     string `json:"create_by"`
	CreateByName string `json:"create_by_name"`
	UpdateBy     string `json:"update_by"`
	UpdateByName string `json:"update_by_name"`
	UpdateTime   string `json:"update_time"`
	StartTime    string `json:"start_time"`
	EndTime      string `json:"end_time"`
	ExecuteTime  string `json:"execute_time"`
}

type DiscoveryRegisterReq struct {
	IP                    string  `json:"ip"`
	Hostname              string  `json:"hostname"`
	CPUCores              int     `json:"cpu_cores"`
	CPUUsedPercent        float64 `json:"cpu_used_percent"`
	CPUFreePercent        float64 ` json:"cpu_free_percent"`
	MemoryTotal           int64   ` json:"memory_total"`
	MemoryUsed            int64   ` json:"memory_used"`
	MemoryFree            int64   ` json:"memory_free"`
	MemoryUsedPercent     float64 ` json:"memory_used_percent"`
	NetworkBytesSent      int64   ` json:"network_bytes_sent"`
	NetworkBytesReceive   int64   `json:"network_bytes_receive"`
	NetworkPacketsSent    int64   ` json:"network_packets_sent"`
	NetworkPacketsReceive int64   ` json:"network_packets_receive"`
}

type DiscoveryRegisterResp struct {
	Success bool                      `json:"success"`
	Message string                    `json:"message"`
	Data    DiscoveryRegisterRespData `json:"data"`
}

type DiscoveryRegisterRespData struct {
	Id                    string  `json:"id"`
	IP                    string  `json:"ip"`
	Hostname              string  `json:"hostname"`
	CPUCores              int     `json:"cpu_cores"`
	CPUUsedPercent        float64 `json:"cpu_used_percent"`
	CPUFreePercent        float64 ` json:"cpu_free_percent"`
	MemoryTotal           int64   ` json:"memory_total"`
	MemoryUsed            int64   ` json:"memory_used"`
	MemoryFree            int64   ` json:"memory_free"`
	MemoryUsedPercent     float64 ` json:"memory_used_percent"`
	NetworkBytesSent      int64   ` json:"network_bytes_sent"`
	NetworkBytesReceive   int64   `json:"network_bytes_receive"`
	NetworkPacketsSent    int64   ` json:"network_packets_sent"`
	NetworkPacketsReceive int64   ` json:"network_packets_receive"`
	IdentificationCode    string  `json:"identification_code"`
}
