// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	demo "osmo-demo/internal/handler/demo"
	"osmo-demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: demo.AuthLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: demo.AuthRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/demo/auth"),
	)
}
